import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "../layout";

export const metadata = {
  title: "Migas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <Layout />;
}
